def complem(stri):
    d =  stri [::-1]
    r = ""
    for c in d:
        if c == "A":
            r += "T"
            
        elif c =="T":
            r +="A"
        elif c =="C":
            r += "G"
        elif c == "G":
            r += "C"
    return r

stri = 'GAAGCGTCAGGCATTTACTCTCAGCTGCGTAGCCCTAGGTCGCGGGCCAACGTGACATCTCTTAACTTCCCCAGCCAGTAGGAGTGCCAGGTCACTCCACTGACTGTGTTATCCAGGTCGGCGCGTAGCCTCGGACCATTGGCATACATCAGGTGGACATCAGCCTAAGCCTAACTCGGATGCCTAGTCGTGGTTGGACTGTTATGATGGGCACTTTCGGGCTTATGGCACGCGGCCAACCATTGTTTTTATCAAACCACGGGACCAAACATATACAGACATTTCACGGTCTATGTCGATTTTCACACCACTGTCCATTACGTTGATTACACAATTCGCTCATTTTGGGCTTACACCCAACACGGTTTGGGAAGATACTCTCGCATCTCCGAAGAAACATGGTGGCCCTATCGGTATCGGCGTTTTTGCTAACGGGCCCTGCCCTGATCCGAAGGCACCCTTGCGAAACGCAAACCCCTGAGTGCACCTAAGTTAATAAAAATAATTACCGATTGTTATTAGCCCTACATTGTCCGTAGAAAAGGGTTAATGTATTTACCAAAACGGAGCCTCTAGCATAGGATCCATAAATCTTTGGTGCATATATACACCCTCTCGCCGACGCCCCTCGGGTTTGAAAAAGGTGCCACATATAGCTTTTAATCCCAGGGATGGAGTTCTTCGGCTATCGGTGTGGCGGTTAAGCCACGCGGTGCATTCCGATCCAGTTCAACTTTTGGTTGATACGAGGATCGACACGGGGTTCACGACCATATTTAAGGTTGTGCGTTTCTAGTTGGGG'
result = complem(stri)

print(complem(stri))
