# -*- coding: utf-8 -*-
"""
Created on Sat Nov 16 10:29:18 2019

@author: Rosa
"""

s = "GGTGACTGTGTCTGGATCGATGTCTGGCTGTCTGGCCACCTTTATTGTCTGGTTGTCTGGTTGTCTGGTTTTTTGTCTGGTGTCTGGTGTCTGGTTGTCTGGAGTGTCTGGCTGAAAGTTATAGCTTGTCTGGGTTGTCTGGAGGTGTCTGGTGTGGTCGTGTCTGGCTGTCTGGTGATGTCTGGATTGTCTGGCATGTCTGGAAAGTGTCTGGATGTCTGGACCCGTGTGTCTGGATTCATTGTCTGGCTGTCTGGTGTGTCTGGGGGTGTCTGGTAATGTCTGGATGTCTGGTGTCTGGATGTCTGGTGTCTGGACCCGCCTGTGTCTGGTTGTCTGGTCTGTCTGGCATCGTGTGTCTGGATTGTCTGGTTGTCTGGGACGGGTTTATGTCTGGTGTCTGGTGTCTGGGATGTCTGGTGTCTGGTGTCTGGTGTCTGGTGTCTGGTGTCTGGCTTCGTGTCTGGGTGTCTGGTGTCTGGGTTGTCTGGTGTCTGGATGCCTGGCTGTAGGCCTGTCTGGCTAAAGCTGTCTGGTGTCTGGTCATGTCTGGGACTTTGTCTGGTGTCTGGCTAATTAGTGTCTGGGAGCTAGTGTCTGGAGCGGTGTGTCTGGCTTGTCTGGTGTCTGGGGCTGAGGGTGTCTGGCGTGTCTGGATGTCTGGACTATGTCTGGCAACTGTCTGGGAAATGAGGTAACTTACTGTCTGGGGTGTCTGGTGTCTGGTGTCTGGACTTTGTCTGGTGTCTGGGTGTCTGGTTGTCTGGATGTCTGGCTGTCTGGTACTGTCTGGCGACACTCATGTCTGGTATGTCTGGTGTCTGGTATGTTGTCTGGAATTGTGTCTGGAATGTCTGGTGTTGTCTGGGTACTTGTCTGGTTGTCTGGTGTCTGGTAACTTGACACGGGAACTGTCTGGGTTTGTCTGGATGTCTGGTGTCTGGGATATGTCTGGTGTCTGGTTGTCTGGTGTCTGGCGTAGCGGTCTGTCTGG"
t = "TGTCTGGTG"

def subs(s,t):
    l = []
    for i in range (0, len(s) - len(t)):
        a = s[i:i+len(t)]
        if (a == t):
            l.append(i+1)
            
    return l

        

            
print(*subs(s,t))           
            